services:
  - type: web
    name: nova-crm-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: camera=(), microphone=(), geolocation=()
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: false
      - key: REACT_APP_API_URL
        value: https://nova-crm-99ca.onrender.com
      - key: REACT_APP_APP_NAME
        value: NOVA Dance Studio CRM
      - key: REACT_APP_VERSION
        value: 1.0.0
